apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-frontend
  template:
    metadata:
      labels: 
        app: guestbook-frontend
    spec:
      containers:
      - name: guestbook-frontend
        image: docker.artifactory.euw.platformservices.io/bpe/guestbook-frontend:1.0.3
        env:
          - name: CONFIG_FILE
            value: /config/config.json
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: frontend-config