apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guestbook-frontend
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-frontend
  template:
    metadata:
      labels: 
        app: guestbook-frontend
    spec:
      containers:
      - name: guestbook-frontend
        image: docker.artifactory.euw.platformservices.io/bpe/guestbook-frontend:1.0.3
        ports:
          - containerPort: 80
        env:
          - name: REDIS_LEADER_SERVICE_HOST
            value: redis-leader
          - name: REDIS_FOLLOWER_SERVICE_HOST
            value: redis-leader